exp_name: 'adfm' # Experiment name
#task_name: ${task_name} # Phase of the experiment. Should be in ['gen_data', 'train_dy','train_edge.yaml','train_critic', 'plan']
log_dir: 'data/adfm/log' # Directory to save logs
seed: 43 # Random seed
real_robot: false # Whether to run on real robot
num_workers: 8 # Number of workers

### ENV ###
env_name: 'ClothDrop' # Environment name
env_shape: null # Shape of the environment : [platform, sphere, rod, random]
render_mode: 'cloth' # Rendering mode. Should be in ['particle', 'cloth']
observation_mode: 'cam_rgb'
partial_observable: true # Whether the environment is partially observable
particle_radius: 0.00625 # Radius of the particles
shape_state_dim: 14 # Dimension of the shape state [xyz, xyz_last, quat(4), quat_last(4)]
action_repeat: 1 # Number of action repeat

# picker
num_picker: 2 # Number of pickers
picker_threshold: 0.625 # always pick a particle
picker_radius: 0.01

# cached states
cached_states_path: 'adfm.pkl' # Path to cached states
num_variations: 1000  # Number of variations of the environment

# domain randomization
vary_cloth_size: false # Whether to vary the size of the cloth
vary_stiffness: false # Whether to vary the stiffness of the cloth
vary_orientation: false # Whether to vary the target orientation of the cloth
vary_mass: false # Whether to vary the mass of the cloth


### DATASET ###
n_rollout: 5000 # Number of rollouts to collect
# time_step: 100 # Time steps per trajectory
dt: 0.01 # 1/100
pred_time_interval: 10 # Interval of timesteps between each dynamics prediction (model dt)
train_valid_ratio: 0.9 # Ratio between training and validation
dataf: './data/adfm/' #Path to dataset
gen_gif: 0 # Whether to also save gif of each trajectory (for debugging)
n_his: 5 # Number of history steps to input to the dynamics

# construct graph
voxel_size: 0.0216 # Size of the voxel
down_sample_scale: 3 # Downsample the simulated cloth by a scale of 3 on each dimension
neighbor_radius: 0.045 # Radius for connecting nearby edges
use_mesh_edge: true # Whether to use mesh edges
use_rest_distance: false # Subtract the rest distance for the edge attribute of mesh edges


defaults:
  - task: gen_data
  - hydra/job_logging: disabled

# set the directory where the output files get saved
hydra:
  output_subdir: null
  run:
    dir: .
